### PR TITLE
Bump version to 0.12

### PR DESCRIPTION
**Pull request by axelson**
Main update is using Cairo

Also update docs and test against Elixir 1.16.0/OTP 26.2

### CODE REVIEW

**Review by crertel — APPROVED** [review]

**Comment by ringlej** [comment]
Has this stalled out over the holidays?
It would be nice to have this version cut :)

**Comment by axelson** [comment]
Yeah it's stalled a bit because I'm noticing some performance degradation when running on my rpi3. And I want to include an upgrade guide to handle the change in background handling that I'm seeing. I hope to get to it soon though!

**Comment by ringlej** [comment]
@axelson @crertel 
I'm not sure what performance degradation you've seen. Can you test using the debug code I added in #63 ?
I'd like to see some traction on this again :)

**Comment by crertel** [comment]
Probably need to kick over CI to figure out why 26.2 isn't building. Pinging @axelson .

**Comment by crertel** [comment]
Pulled this work into #76 .

**Pull request closed without merging**
