### PR TITLE
Pull in rrectv work

### PR DESCRIPTION
**Pull request by crertel**
This finishes pulling in @GPrimola 's work that I merged in #17 .

We'll rebase here and have  staging ground to pull in the functionality to the Cairo backend too.

### CODE REVIEW

**Comment by crertel** [comment]
Ah, hell's bells...okay @ringlej I'm caught back up on this--is there any chance you can grab the Cairo side of this, or should I grab it? I think you've got a bit more context there than I do.

**Comment by ringlej** [comment]
The only thing I'd mention here is that there isn't a Cairo implementation provided so anyone using it with Cairo will get a log message if the function is attempted with no rendering done.
That said, I'd rather this not hold up a release.

**Comment by ringlej** [comment]
Right now I don't have the cycles to tackle this for Cairo.

**Comment by crertel** [comment]
Makes sense. Let's do a fast-follow then.

**Comment by GPrimola** [comment]
@crertel @ringlej I can do it for Cairo too! I'm almost sure when I did it for NVG there wasn't support for Cairo yet. Maybe? 🤔
Anyway, will do it in another PR.
Thanks!! :)

**Comment by crertel** [comment]
'preciate ya, @GPrimola!

**Pull request merged**
