### PR TITLE
add alpha channel to sprites

### PR DESCRIPTION
**Pull request by seb3s**
This PR adds an optional alpha channel to sprite commands. There is a corresponding PR in scenic to handle that change.

### CODE REVIEW

**Comment by crertel** [comment]
@seb3s , sorry for the delay--would you mind rebasing this, if you still want to go forward? We moved around a bunch of things in the pursuit of Cairo backend.

**Comment by seb3s** [comment]
I did some changes, hope this helps (not sure about the cairo modifications)

**Comment by crertel** [comment]
Thank you again @seb3s !

We'd need to land this concurrent with some changes to scenic proper, probably over [here](https://github.com/ScenicFramework/scenic/blob/main/lib/scenic/primitive/sprites.ex) and possibly elsewhere, I think. Does that sound about right?

**Comment by seb3s** [comment]
Hello,
I have opened this PR a long time ago for that part:
https://github.com/ScenicFramework/scenic/pull/315/files
cheers,
Sébastien.

**Review by crertel — APPROVED** [review]

**Pull request merged**
