### PR TITLE
Fix incorrect font width calculation in fontstash

### PR DESCRIPTION
**Pull request by JediLuke**
This PR is probably not ready to merge, but I'm sharing it here to make the information public for anyone else facing text-alignment issues...

This PR has 2 main changes.

1) I changed `breakRowWidth` from 1000 to 10000, just to bypass the line-wrap that occurs on long lines
2) I removed the logic inside `fontstash.h` which rounds the glyph width of each character to the nearest integer, to be more accurate with what the FontMetrics package (and the canvas implementation, based on your testing as we discussed in Slack) gives us. It isn't perfect, there's still some inaccuracies, but it's "good enough" for my personal projects (QuillEx & Flamelex). It seems perfect for monospaced fonts with no spacing, but some other fonts e.g. Roboto-Regular and fira-code (which is actually monospaced, but maybe has extra spacing between letters??) it's still a tiny bit off.

### CODE REVIEW

**Comment by JediLuke** [comment]
The calculation is still not perfectly the same as FontMetrics:
```
int font = nvgCreateFont(vg, "sans", "./IBMPlexMono-Regular.ttf");
nvgFontSize(vg, 24.0f); 
char text[] = "LukeLukeLukeLuke";
float widthLuke = nvgTextBounds(vg, 0,0, text, NULL, NULL);
printf("Luke width: %f", widthLuke);
```

Gives a value of `width: 230.399963`, whereas FontMetrics gives:

```
iex(4)> FontMetrics.width("LukeLukeLukeLuke", 24, m)
236.30769230769232
```

However, I guess that somehow this is at least "good enough" for me eye-balling the text alignment.

**Comment by boydm** [comment]
I figured out the remaining error.

fontstash is pre-calculating the xadv for each character based on the bounding box from the font (which is based on integers), then multiplying by the scale factor, resulting in a float. But that float is then cast into a short (integer) and stored into the fontstash, creating a rounding error per character.

So, please make the folllowing updates, all in fontstash

Line 386
```
	short xadv,xoff,yoff;
```
Should become
```
	short xoff,yoff;
	float xadv;
```


Line 1158
```
	glyph->xadv = (short)(scale * advance * 10.0f);
```
should become
```
	glyph->xadv = scale * advance * 10.0f;
```

This completely fixes the rest of the errors for me. Yay!

**Comment by boydm** [comment]
Hey Luke. As we discussed in Slack, please remove the line break change. I think that should become a new :line_break style that gets added to v0.12

Would also need testing in the remote driver which I'm not prepared to do right now...

**Comment by JediLuke** [comment]
- Removed line-break change
- added your additional integer cast error fixes

It now renders very nicely, as discussed it still seems like we get some tiny differences when computing the widths. I have a local nanoVG where I'm just compiling a pure C app which is how I was able to get it to print the values out, my nanoVG code looks like this:
```
// in the initialization section
int font = nvgCreateFont(vg, "sans", "./IBMPlexMono-Regular.ttf");

// then, inside the drawing loop...
        nvgFontSize(vg, 24.0f); 
        char text[] = "LukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLukeLuke";
        float widthLuke = nvgTextBounds(vg, 0,0, text, NULL, NULL);
        printf("Luke width: %f", widthLuke);
 ```
 
 This prints `Luke width: 1612.801636`
 
 When I use `FontMetrics.width/3`, it gives `1612.8`... good enough for me :P

**Pull request merged**
